### ISSUE TITLE
Testirat komunikacijo na Arduinu

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#10]
ADD FUCKING DESCRIPTION, YOU NOOB!

**Comment by grizeldi** [comment]
Po nekaj zezanja pogruntal, da ideja da bi pošiljal bajte ni tok napačna...

**Comment by mucamaca** [comment]
Pa ne vem. Na arduinu je treba tud mal sparat space, pa tekst ni 
najboljsa zadeva za to. Zakaj je pa lazi delat?

**Comment by grizeldi** [comment]
A ti ne kaze edita?
Bajti so super za to delat kar rabmo sam arduino ide serial monitor tut stevilke posilja kot char...
Pol ka sm pa do konca spisu Java del je pa delal.

**Comment by mucamaca** [comment]
a zdej so tud u javi byti?

**Comment by mucamaca** [comment]
ne stekam, jave pa ne berem zadost dobr

**Comment by mucamaca** [comment]
nobody likes you. imma close this
