### ISSUE TITLE
Testirat komunikacijo na Piju

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#11]
Enkrat cez dolgo dolgo casa...

**Comment by mucamaca** [comment]
ta tip itak nc ne dela
zaprimo to.

**Comment by grizeldi** [comment]
Nop, na Piju pa se nisem testiru. Ce se prou spomnm so imena USB portov neki drgacna al neki.

**Comment by mucamaca** [comment]
ok sori

**Comment by mucamaca** [comment]
meiw

**Comment by mucamaca** [comment]
meiw

**Comment by grizeldi** [comment]
Maš zdej kvazidelujočo verzijo na branchu FXGUI, stestiri.

**Comment by mucamaca** [comment]
lahko bi me bol prijazno prosil, mladi gospodiç.

**Comment by mucamaca** [comment]
a bi lahko providu en jar file, ki ga samo zalaufas in dela? sej ves, da nisem vesc jave. pa vse dependecyjev pa tega.

**Comment by grizeldi** [comment]
Uradno sprobano in dela
