### ISSUE TITLE
add .idea to .gitignore

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#12]
@grizeldi Kaj ce bi ti dodal .idea folder v .gitignore, zato, da ni tm enga nepotrebenga folderja pa 1000 xml filov?

**Comment by grizeldi** [comment]
Folder je potrebn, da lahko drugi odpirate IDEA projekt.

**Comment by grizeldi** [comment]
.idea folder ima svoj namen in sicer zato, da IntelliJ prepozna folder kot projekt. In zdj se pa plz že nehi mešat u java del. I can handle it.

**Comment by mucamaca** [comment]
ok, sam xml mi dela mal zmede tko generalno.

**Comment by mucamaca** [comment]
btw kako ti je vsec label?
