### ISSUE TITLE
Noben nic ne dela

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#14]
# Kva je zdej to????

**Comment by mucamaca** [comment]
@grizeldi @ogenjcek @MaticJeCar Nic ne delate, ze dva tedna ni nobenga commita razen mene pa grizeldija sploh _nic?!?!?!?!?!_

**Comment by grizeldi** [comment]
@mucamaca razlog je enostaven. Capudra ni nikjer in ostale ekipe tudi nič
ne delajo. Meni se zdi brezveze neki matrat za nekaj kar potem sploh ne bo
uporabljeno. Naj najprej ostali kaj naredijo, potem pa se spet pridružujem
programiranju. BTW: Uspoosbl smo 3D printer. Kind of.

**Comment by mucamaca** [comment]
A bo kdo mogoč za težil na fb skupini??

K če ne bo, pol očitno res ne bo nc.

2015-12-26 17:04, je grizeldi napisal

**Comment by mucamaca** [comment]
To sploh ni issue. To je vzdih, ki ni izpolnil svojega namena in poslanstva.
Najboljs, da ga closam
