### ISSUE TITLE
PCArduinoTalker  v Pi_java_stuff

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#15]
A je kaksen poseben vzrok za to, da si za to naredu nov IDEA project v posebnem folderju, al je blo to iz cistga dolgcajta, al si hotu mal dodatnih vrstic naspamat al kaj?

**Comment by grizeldi** [comment]
Ne. PcToArduinoTalker ima z mal modifikacijami uporabno vrednost tud izven tega projekta, zato sem ga dal posebi.

**Comment by mucamaca** [comment]
a pol nardiva nov repo al kaj?
