### ISSUE TITLE
Pogruntat protokol za serial komunikacijo

### ISSUE THREAD

**Issue by grizeldi** [mucamaca/vic-palacinke#16]
Treba je izumit katera koda bo kaj pomenila in to zapisat v en txt.
Pomoje je najbolje da ima en paketek (sporocilo) 3 bajte:
1. bajt: koda sporocila
2. bajt: prvi del podatka
3. bajt: drugi del podatka

V tist txt pa sam napismo kaj je kjera koda pa kaj pomeni podatek.

**Comment by mucamaca** [comment]
zakaj prvi in drugi del podatka?
mislm da bi bil en bajt za podatek cist zadost.
@grizeldi razlozi mi prosim

**Comment by mucamaca** [comment]
Bom jez to naredu

**Comment by grizeldi** [comment]
Si kdaj pomislu da je lohk podatek vecji od 255 (oziroma 127 v primeru
jave)?

**Comment by mucamaca** [comment]
ja, sam se ne spomnem nobenga tazga podatka, ki bil relevanten za tele 
palacinke

**Comment by grizeldi** [comment]
Obrnjenost stepper motorja (ma 400 korakov).

**Comment by mucamaca** [comment]
ok, sam zakaj bi to posiljal piju pa tut lahko delis z dva pa bo se zmer 
blazno natancno

**Comment by mucamaca** [comment]
se kej?

**Comment by grizeldi** [comment]
To ma point. Ampak lahko pa pol posles dva podatka z eno komando.

**Comment by mucamaca** [comment]
to je nesmiselno.
pol ne ves, kaj pomen ta drugi podatek
itak te pa nc ne stane, ce posles pol dve komandi po en podatek.
pa se racuni, da je en arduino integer 16 bitov, tko da se ena komanda z enim podatkom lih lepo stisne notr

**Comment by grizeldi** [comment]
Oki. Cr bo treba itak lahko naknadno spremenimo nazaj na 3 bajte.

**Comment by mucamaca** [comment]
prav.
mal off-topic: v kirem programu se nardi 3d model, ki ga das cnc-ju da izrezka?

**Comment by mucamaca** [comment]
jaz moram it, ker gremo druzinsko tect. adijo.
cez uro pa pol bom nazaj

**Comment by mucamaca** [comment]
AAnd im back

**Comment by grizeldi** [comment]
A si ze naredu?

**Comment by mucamaca** [comment]
ne

**Comment by mucamaca** [comment]
yu is maca

**Comment by mucamaca** [comment]
ja

**Comment by mucamaca** [comment]
koncni izdelk je u serial-protokol.txt
ce komu kej ni prov naj pove.
