### ISSUE TITLE
narest neki, kar bo handlal log stuff v javi

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#17]
ena stvar, ki bere serial in  logging  del preusmer nekam, in potem tisti nekam to analizira, pa zapise v file, kar se da potem tud kot debug info uporabljat. pa ta najpomembnejse stvari napise tud na gui.

**Comment by mucamaca** [comment]
matic se vsaj neki trud,ceprav pomojem ni niti se odprl githuba od takrat ko smo ga dodal kot collaboratorja, tko da bos ti to naredu.

**Comment by mucamaca** [comment]
ce kej ne stekas, kar vprasi.

**Comment by grizeldi** [comment]
Seprav hoces da se vse kar pride iz seriala zapise v file predn ga lahko
dobi ostala koda?
A bi bla konzola za zacetek ok?

**Comment by grizeldi** [comment]
Vse kar pride iz seriala al sam tekst bajtov pa ne?
To bi blo precej tezko...

**Comment by mucamaca** [comment]
ne cist tko ti  pol povem

**Comment by mucamaca** [comment]
niti ne.

**Comment by grizeldi** [comment]
Done.
