### ISSUE TITLE
Prepovedat Boru da dela .h fileje

### ISSUE THREAD

**Issue by grizeldi** [mucamaca/vic-palacinke#18]
ARDUINO IDE SAM ZLEPI SKUPAJ .INO FILEJE ZATO PROSIM NEHI DELAT .H FILEJE KA SO NEPOTREBNI IN MI GREJO NA JETRA!!!!

**Comment by mucamaca** [comment]
ju is retarded

**Comment by mucamaca** [comment]
ta stvar je do sedaj najbolj retardirana od vsega pri arduino IDEju.

**Comment by mucamaca** [comment]
amapk ok.
