### ISSUE TITLE
GUI za raspberry pi

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#2]
Naredi grafičn interface za pi v JAVI. sej boš znal, a ne?

**Comment by grizeldi** [comment]
Yes, sir!

**Comment by grizeldi** [comment]
Ob izdelavi sem mimgrede naredu še framework za Matevža, ki pa bo mogu uporabt intellij , ker je sem uporabu pi plugin...

**Comment by mucamaca** [comment]
Ja. Dobr. Sam ta tip mi ne odgovarja na maile. A mu napises na fb al pa 
mi das njegovo cifro, ce jo mas?

**Comment by grizeldi** [comment]
Jaz ne imeti cifro ali fb biti...

**Comment by mucamaca** [comment]
dobr indijanec

**Comment by mucamaca** [comment]
@grizeldi a bi se dal narest tko, da je GUI fullscreen in da se nc okoli ne vidi okvirja od okna?
To bi blo super.
Nasu sm Matevza na githubu. Ogenjcek mu je ime

**Comment by grizeldi** [comment]
Lahka nucam JWindow namest JFrame, če ti gre un border na vrh na jetra.

**Comment by mucamaca** [comment]
Tocno to sm mislu :+1: . Zato, da na piju user ne bo mogu drezat po drugih stvareh ampak bo omejen na ta nas gui. Matevz si je naredu GitHub! ime mu je ogenjcek.(!)

**Comment by mucamaca** [comment]
To lohk se mal pocaka

**Comment by mucamaca** [comment]
Oh no, it's retarded!

**Comment by mucamaca** [comment]
kako kej gre tale GUI?

**Comment by mucamaca** [comment]
Meow

**Comment by mucamaca** [comment]
Tole pa ni priority. Removite label.

**Comment by mucamaca** [comment]
dej nared ze to!

**Comment by grizeldi** [comment]
Ukin use teste, sprašvanja pa poročila za glasbo pa ti grem lahko takoj
delat.

**Comment by mucamaca** [comment]
kaj pa pojektno pa antidepresive?

**Comment by grizeldi** [comment]
Kle mamo zdj se tima. Dve uri sva rabla ampak zdj mislm da prblizn zastop kako zadeve funkcionirajo.

**Comment by mucamaca** [comment]
dobr.

**Comment by grizeldi** [comment]
Prva varjanta je #32

**Comment by mucamaca** [comment]
MEow
meOW

**Comment by mucamaca** [comment]
No GUI - 
no issues with it.
