### ISSUE TITLE
Make snake on LCD

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#25]
Make a snake game when ju have too much time (now)

**Comment by mucamaca** [comment]
Skori končano!

**Comment by grizeldi** [comment]
Še mal pa bo delal

**Comment by mucamaca** [comment]
Se cist mal

**Comment by mucamaca** [comment]
this side project has (ilegally) migrated to mucamaca/arduino-games (https://github.com/mucamaca/arduino-games)

**Comment by 11matic** [comment]
Squids.
