### ISSUE TITLE
Arduino side Arduino - Pi komunikacija

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#3]
Naredi funkcije za komunikacijo s Pijem za Arduino v C

**Comment by grizeldi** [comment]
Kaj pa pi side? Moje delo (v Javi?)?

**Comment by mucamaca** [comment]
Če jaz kej vem sva rekla da bo ta del naredu un matevž, sam si še ni 
githuba naredu in mu zatorej ne morem taskov assignat...

**Comment by mucamaca** [comment]
No more WIP.
Finished!

**Comment by mucamaca** [comment]
Se enkrat. Tokrat prek usb seriala

**Comment by grizeldi** [comment]
Js sm ti zrihtu glihkr java side class ki bere/piše na arduino, ti pa zrihti arduino lib ki to nardi (velik manj dela :D)

**Comment by grizeldi** [comment]
Done prek seriala
