### ISSUE TITLE
Popravit in dopolnit arduino debug filter, da bo skladen MeWP protokolom

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#35]
protokol je definiran v MeWP specifikacija.txt

**Comment by grizeldi** [comment]
Bullshit. Najpri zrihti ime pa specifikacijo tko da bo smiselno, pol pa bom kej naredu.

**Comment by mucamaca** [comment]
ja ni se koncano.

**Comment by mucamaca** [comment]
a prides jutr na zavod?

**Comment by mucamaca** [comment]
a ves da je bil rms enkrat v Sloveniji?

**Comment by grizeldi** [comment]
Kill it.

**Comment by mucamaca** [comment]
ni ga vec v sloveniji. poleg tega je prov car.

**Comment by mucamaca** [comment]
a ves da sem napisu awesome linux device driver, ki se imenuje /dev/meow in vsakič ko poskušaš brat z njega prebereš meow.

**Comment by mucamaca** [comment]
zdej ni več neuporaben

**Comment by grizeldi** [comment]
Kje se naštela na githubu da enga ignoraš?

**Comment by mucamaca** [comment]
A ti šalca teži al kaj?

**Comment by mucamaca** [comment]
A ves, da ima ta issue ze celih 11 kommentov

**Comment by grizeldi** [comment]
meow Po novem sm te blokiru.
Ko bos meu kej pametnga za povedat mi pa posl mejl. Ce mi bos pa se tm sranje posilju te bom pa se tm u spam prestavu.

**Comment by mucamaca** [comment]
Misl da salca ne gleda tega, tko da mu lahk ti posles mail

**Comment by mucamaca** [comment]
no, zdaj mislm, da je vse skupaj v redu napisan. se preimenoval sem tist file.
btw linux kernel  4.0 je bil codenamed Hurr Durr ima a sheep.

**Comment by mucamaca** [comment]
4.7 je pa Psychotic stoned sheep.

**Comment by grizeldi** [comment]
Jamal, you is stupid!
Blokiral sem uporabika @mucamaca.
In tist gor je tut veljal teb. Bolnih for pačni treva quotat.

**Comment by mucamaca** [comment]
Ja vem.

**Comment by mucamaca** [comment]
mjau!
