### ISSUE TITLE
Popravi palačinke.fzz file, tko da bo usklajen s tistim, kar smo se odločl prejšnjo soboto

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#4]
če kej ne veš lahko vprašaš prek teh komentarjev.

**Comment by mucamaca** [comment]
pa prosim ko prebereš in začneš delat na tej zadolžitvi dodaj label WIP (work in progress)

**Comment by mucamaca** [comment]
Aha, še to. Opreš se lahko pa na vezave.txt, ki ga bom pa jaz updatu.

**Comment by grizeldi** [comment]
In kaj ste se zmenl prejšno soboto? A kej drgač ka u petk?

**Comment by mucamaca** [comment]
Ubistvu ne, sam bl u detajle. Zakaj se sam ti odzivas na moje poste un 
tip k mu je to namenjen pa ne?

**Comment by grizeldi** [comment]
Ker normalni ldje uporablajo fb. #motoričnide...

**Comment by mucamaca** [comment]
sej lohk do konca napises.

**Comment by mucamaca** [comment]
Tip nima facebooka! HA!

**Comment by mucamaca** [comment]
Just forget about .fzz thing
