### ISSUE TITLE
update vezave.txt

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/vic-palacinke#5]
posodobi vezave.txt file da bo se bo skladal z zadnjim dogovorom
če ma kdo lakšen predlog naj kr komentira pa bom popravu.

**Comment by mucamaca** [comment]
Ja! imamo ze dva zaprta issua!

**Comment by mucamaca** [comment]
ne vem komu, nevem kdaj in nevem zakaj se bo komu dal tole urejat. men se ne bo. ker ne vem kaj je sploh reba narest.

**Comment by grizeldi** [comment]
To kr capudru assignaj :smile:

**Comment by mucamaca** [comment]
dobra ">

**Comment by mucamaca** [comment]
nobody cares about this file any more. we now has constant.ino

**Comment by grizeldi** [comment]
Gup yup. Lahk zapres

**Comment by mucamaca** [comment]
sej sem ze. gup yup
