### ISSUE TITLE
Mal popucat repozitorij

### ISSUE THREAD

**Issue by grizeldi** [mucamaca/vic-palacinke#7]
Random fileje bi blo treba popredalčkat po folderjih in zradirat nepotrebno šaro.

**Comment by grizeldi** [comment]
Sm hotu dodt labele, ampak mobiln github je dizaster.

**Comment by mucamaca** [comment]
sploh nism vedu, da obstaja

**Comment by grizeldi** [comment]
A lohk ti to nardis?
Sm te hotu assignat, pa na mobile ne dela.

**Comment by mucamaca** [comment]
Ja bom

**Comment by mucamaca** [comment]
Labelu sm ga nobenu se ne da. True story

**Comment by grizeldi** [comment]
LOL
Sj b js nared sam nism doma, pol se morm pa nemo ucit.

**Comment by mucamaca** [comment]
Good luck with nema. Bom pa ze jaz zrihtu
zapiram pa issueje ko nor. Tale bo ze drugi. Na sreco se jih da reopenat :8ball: dont ask me why

**Comment by mucamaca** [comment]
No pa je

**Comment by grizeldi** [comment]
ČŽŠ ji pa presledki sprobano delajo na malini, tko v nanotu kot če jih zalaufaš s pythonom, tko da pucanje se nadaljuje!

**Comment by grizeldi** [comment]
Pa odloč se že kakšn bo ime, ka vsakič ka renamaš folder mi čist zjebe Ideo, pa morm na novo odpirat pa zapirat...

**Comment by mucamaca** [comment]
Ok. Sam cist iz profesionalnosti in tega, da ce nimas default keymapa na slo na piju ne mors pisat not sumnikov poskusi ne met presledkov in sumnikov v file in folder namih

**Comment by grizeldi** [comment]
Lahko pišeš šumnike in presledke. Sprobano. NWM pa če se da direktno, ampak prek Puttya se da

**Comment by mucamaca** [comment]
putty sucks. use ssh command. Prosm lepo, dej brez sumnikov pa presledkov

**Comment by mucamaca** [comment]
Zakaj mas pet folderjev enga v drugem v sourcu?

**Comment by mucamaca** [comment]
Ful me ma, da bi to zbrisu.

**Comment by grizeldi** [comment]
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by grizeldi** [comment]
Zj pa prosm nehi popravlat zadeve, ka niso pod tvojo domeno in ne veš čemu služjo.

**Comment by mucamaca** [comment]
too late

**Comment by mucamaca** [comment]
sorry

**Comment by mucamaca** [comment]
se dobr, da ma github commit history
