### ISSUE TITLE
Uskladit Pi in Arduino del komunikacije

### ISSUE THREAD

**Issue by grizeldi** [mucamaca/vic-palacinke#8]
Treba je uskladit komunikacijo med pijem in arduinotom.

**Comment by mucamaca** [comment]
I will probably have to do this all by myself.

**Comment by grizeldi** [comment]
Narjeno. Sam Windows je retardiran in ne dela na njem. Na Ubuntuju vse dela super. Koda je v PCToArduinoTalker in v Arduino_C_things/testing/komunikacija.

**Comment by mucamaca** [comment]
ce arduino del ni niti narjen, kako lohk to zapres?

**Comment by mucamaca** [comment]
Oh no, it's RETARDED.

**Comment by grizeldi** [comment]
Je narjen. Framework je narjen. Kaj bomo pa posiljal je pa tema ksnga druzga issueja.

**Comment by mucamaca** [comment]
uredu, sej mas prov
